using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum TrybDzia쓰nia {celKarta, celWrug};

public class celLinia : MonoBehaviour
{
    public Transform podparcie1, podparcie2;
    public LineRenderer lineRenderer;
    private float poprawkaWysoko띾iPojedy刃za = 2f;
    [HideInInspector] public Vector3 pocz졊ek, koniec;
    [HideInInspector] public TrybDzia쓰nia trybDzia쓰nia;
    private Vector3 pocz졊ekVwzgl師nam, koniecVwzgl師na;

    void Update()
    {
        if (pocz졊ek != null && koniec != null)
        {
            if (trybDzia쓰nia == TrybDzia쓰nia.celKarta)
            {
                PodparciePojedy刃ze(pocz졊ek, koniec);
                RysyujLinie1(pocz졊ek, podparcie1.position, koniec);
            }
            else if (trybDzia쓰nia == TrybDzia쓰nia.celWrug)
            {
                PodparciePodwujne(pocz졊ek, koniec);
                RysyujLinie2(pocz졊ek, podparcie1.position, podparcie2.position, koniec);
            }
        }
    }

    private void PodparciePojedy刃ze(Vector3 Pocz졊ek, Vector3 Koniec)
    {
        Vector3 newPoz = new Vector3(Pocz졊ek.x + Koniec.x, Pocz졊ek.y + Koniec.y, Pocz졊ek.z + Koniec.z) / 2;
        float plusY = Mathf.Abs(Pocz졊ek.y - Koniec.y);
        newPoz.y += (plusY + poprawkaWysoko띾iPojedy刃za);
        podparcie1.position = newPoz;
    }
    private void PodparciePodwujne(Vector3 Pocz졊ek, Vector3 Koniec)
    {
        Vector3 newPoz1 = new Vector3(Pocz졊ek.x, Koniec.y, Pocz졊ek.z);
        Vector3 newPoz2 = new Vector3(Koniec.x, Pocz졊ek.y, Koniec.z);   
        podparcie1.position = newPoz1;
        podparcie2.position = newPoz2;
    }

    private void RysyujLinie1(Vector3 Pocz졊ek, Vector3 p1, Vector3 Koniec)
    {
        lineRenderer.positionCount = 200;
        float t = 0f;
        Vector3 B = new Vector3(0, 0, 0);
        for (int i = 0; i < lineRenderer.positionCount; i++)
        {
            B = (1 - t) * (1 - t) * Pocz졊ek + 2 * (1 - t) * t * p1 + t * t * Koniec;
            lineRenderer.SetPosition(i, B);
            t += (1 / (float)lineRenderer.positionCount);
        }
    }
    private void RysyujLinie2(Vector3 Pocz졊ek, Vector3 p1, Vector3 p2, Vector3 Koniec)
    {
        lineRenderer.positionCount = 200;
        float t = 0f;
        Vector3 B = new Vector3(0, 0, 0);
        for (int i = 0; i < lineRenderer.positionCount; i++)
        {
            B = (1 - t) * (1 - t) * (1 - t) * Pocz졊ek + 3 * (1 - t) * (1 - t) *
                t * p1 + 3 * (1 - t) * t * t * p2 + t * t * t * Koniec;

            lineRenderer.SetPosition(i, B);
            t += (1 / (float)lineRenderer.positionCount);
        }
    }
}
