using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class hp : MonoBehaviour
{
    public GameObject w쓰띾icielZdrowia;
    private GameObject bar, barText, pancerzIcon, pancerzLicznik;

    void Awake()
    {
        bar = this.gameObject.transform.GetChild(1).gameObject; 
        barText = this.gameObject.transform.GetChild(2).gameObject;
        pancerzIcon = this.gameObject.transform.GetChild(3).gameObject;
        pancerzLicznik = pancerzIcon.transform.GetChild(0).gameObject;
    }
    void Update()
    {
        if(w쓰띾icielZdrowia != null)
        {
            StanZdrowiaPokarz();
            PacerzPokasz();
        }
    }

    private void StanZdrowiaPokarz()
    {
        if(w쓰띾icielZdrowia.tag == "Player")
        {
            float x = w쓰띾icielZdrowia.GetComponent<playerEq>().hp / w쓰띾icielZdrowia.GetComponent<playerEq>().hpMax;
            bar.transform.localScale = new Vector3(x, 1f, 1f);
            barText.GetComponent<TextMeshPro>().text = w쓰띾icielZdrowia.GetComponent<playerEq>().hp.ToString() + "/" + w쓰띾icielZdrowia.GetComponent<playerEq>().hpMax.ToString();
        }
        else
        {
            float x = w쓰띾icielZdrowia.GetComponent<WRUG1>().hpAktualne / w쓰띾icielZdrowia.GetComponent<WRUG1>().hpMax;
            bar.transform.localScale = new Vector3(x, 1f, 1f);
            barText.GetComponent<TextMeshPro>().text = w쓰띾icielZdrowia.GetComponent<WRUG1>().hpAktualne.ToString() + "/" + w쓰띾icielZdrowia.GetComponent<WRUG1>().hpMax.ToString();
        }
    }

    private void PacerzPokasz()
    {
        if(w쓰띾icielZdrowia.tag == "Player")
        {
            playerEq eq = w쓰띾icielZdrowia.GetComponent<playerEq>();
            if(eq.aktualnyPancerz > 0)
            {
                pancerzIcon.SetActive(true);
                pancerzLicznik.GetComponent<TextMeshPro>().text = eq.aktualnyPancerz.ToString();
            }
            else
            {
                pancerzIcon.SetActive(false);
            }
        }
        else
        {
            WRUG1 wr = w쓰띾icielZdrowia.GetComponent<WRUG1>();
            if(wr.aktualnyPancerz > 0)
            {
                pancerzIcon.SetActive(true);
                pancerzLicznik.GetComponent<TextMeshPro>().text = wr.aktualnyPancerz.ToString();
            }
            else
            {
                pancerzIcon.SetActive(false);
            }
        }
    }
}
